use napi::bindgen_prelude::*;
use serde_json::{json, Value};

use super::super::service::McpService;
use super::super::tools::McpTool;

const SERVER_ID: &str = "workflow";

/// WorkFlow Mode's dedicated tool server: validates and normalizes the
/// workflow graph generated by the model. The desktop UI (React Flow) renders
/// the graph from the tool call arguments, lets the user edit per-node API
/// profile / model / prompt, and drives execution node by node after the user
/// presses the confirm button.
pub struct WorkflowService;

impl WorkflowService {
    pub fn new() -> Self {
        WorkflowService
    }

    fn generate(&self, args: &Value) -> napi::Result<Value> {
        let title = args
            .get("title")
            .and_then(|v| v.as_str())
            .map(str::trim)
            .unwrap_or("")
            .to_string();

        let nodes = match args.get("nodes") {
            Some(Value::Array(items)) => items
                .iter()
                .filter_map(|item| item.as_object())
                .map(|node| {
                    let id = node.get("id").and_then(|v| v.as_str()).unwrap_or("");
                    let name = node
                        .get("name")
                        .and_then(|v| v.as_str())
                        .unwrap_or(id);
                    let label = node
                        .get("label")
                        .and_then(|v| v.as_str())
                        .filter(|v| !v.trim().is_empty())
                        .unwrap_or(name);
                    let prompt = node.get("prompt").and_then(|v| v.as_str()).unwrap_or("");
                    let description = node
                        .get("description")
                        .and_then(|v| v.as_str())
                        .unwrap_or("");
                    let api_profile = node
                        .get("apiProfile")
                        .and_then(|v| v.as_str())
                        .unwrap_or("")
                        .trim()
                        .to_string();
                    let model = node
                        .get("model")
                        .and_then(|v| v.as_str())
                        .unwrap_or("")
                        .trim()
                        .to_string();
                    json!({
                        "id": id,
                        "name": name.trim(),
                        "label": label.trim(),
                        "prompt": prompt.trim(),
                        "description": description.trim(),
                        "apiProfile": api_profile,
                        "model": model,
                    })
                })
                .collect::<Vec<Value>>(),
            _ => Vec::new(),
        };

        let edges = match args.get("edges") {
            Some(Value::Array(items)) => items
                .iter()
                .filter_map(|item| item.as_object())
                .map(|edge| {
                    json!({
                        "source": edge.get("source").and_then(|v| v.as_str()).unwrap_or(""),
                        "target": edge.get("target").and_then(|v| v.as_str()).unwrap_or(""),
                    })
                })
                .collect::<Vec<Value>>(),
            _ => Vec::new(),
        };

        let (order, errors) = validate_graph(&nodes, &edges);
        let valid = errors.is_empty();

        Ok(json!({
            "valid": valid,
            "title": title,
            "nodes": nodes,
            "edges": edges,
            "order": order,
            "errors": errors,
        }))
    }
}

/// Topological sort (Kahn's algorithm) plus structural validation.
/// Returns the execution order of node ids and a list of validation errors.
/// Shared by the MCP tool (workflow-generate) and the `validate_workflow_graph`
/// NAPI export so the desktop runner and the model see exactly one topology
/// implementation (no duplicated sort/cycle logic on the renderer side).
pub(crate) fn validate_graph(nodes: &[Value], edges: &[Value]) -> (Vec<String>, Vec<String>) {
    let mut errors: Vec<String> = Vec::new();
    let mut node_ids: Vec<String> = Vec::new();
    let mut seen: std::collections::HashSet<String> = std::collections::HashSet::new();

    for node in nodes {
        let id = node
            .get("id")
            .and_then(|v| v.as_str())
            .unwrap_or("")
            .to_string();
        if id.trim().is_empty() {
            errors.push("Every node must have a non-empty id".to_string());
        } else if !seen.insert(id.clone()) {
            errors.push(format!("Duplicate node id: {id}"));
        } else {
            node_ids.push(id);
        }
        let prompt = node.get("prompt").and_then(|v| v.as_str()).unwrap_or("");
        if prompt.trim().is_empty() {
            errors.push(format!(
                "Node {} has an empty prompt — every node needs a self-contained instruction prompt",
                node.get("id").and_then(|v| v.as_str()).unwrap_or("?")
            ));
        }
    }

    let mut in_degree: std::collections::HashMap<String, usize> = node_ids
        .iter()
        .map(|id| (id.clone(), 0usize))
        .collect();
    let mut adjacency: std::collections::HashMap<String, Vec<String>> =
        std::collections::HashMap::new();
    let node_set: std::collections::HashSet<String> = seen.clone();

    for edge in edges {
        let source = edge
            .get("source")
            .and_then(|v| v.as_str())
            .unwrap_or("")
            .to_string();
        let target = edge
            .get("target")
            .and_then(|v| v.as_str())
            .unwrap_or("")
            .to_string();
        if !node_set.contains(&source) {
            errors.push(format!("Edge references unknown source node: {source}"));
            continue;
        }
        if !node_set.contains(&target) {
            errors.push(format!("Edge references unknown target node: {target}"));
            continue;
        }
        if source == target {
            errors.push(format!("Self-loop edge detected on node: {source}"));
            continue;
        }
        if let Some(degree) = in_degree.get_mut(&target) {
            *degree += 1;
        }
        adjacency.entry(source).or_default().push(target);
    }

    // Kahn's algorithm: repeatedly remove nodes with zero in-degree.
    let mut queue: std::collections::VecDeque<String> = in_degree
        .iter()
        .filter(|(_, degree)| **degree == 0)
        .map(|(id, _)| id.clone())
        .collect();
    let mut order: Vec<String> = Vec::new();
    while let Some(node) = queue.pop_front() {
        order.push(node.clone());
        if let Some(children) = adjacency.get(&node) {
            for child in children {
                if let Some(degree) = in_degree.get_mut(child) {
                    *degree -= 1;
                    if *degree == 0 {
                        queue.push_back(child.clone());
                    }
                }
            }
        }
    }

    if order.len() != node_ids.len() {
        errors.push(
            "Workflow graph contains a cycle — nodes must form an acyclic graph (a DAG)"
                .to_string(),
        );
    }

    (order, errors)
}

impl McpService for WorkflowService {
    fn id(&self) -> &str {
        SERVER_ID
    }

    fn tools(&self) -> Vec<McpTool> {
        vec![
            McpTool {
                server_id: SERVER_ID.to_string(),
                name: "workflow-generate".to_string(),
                description: "Generate/validate a WorkFlow graph. Call this ONCE with the complete workflow: nodes (id, name, label, prompt, description, apiProfile, model) plus edges (source -> target). The graph must be an acyclic DAG; the desktop UI renders it as an interactive flow chart where the user edits per-node API profile, model and prompt, then confirms execution. Nodes whose dependencies are all met run concurrently, each in its own conversation with its own API config/model, receiving the merged <handoff> documents of all its direct predecessors (a node without predecessors receives none) and producing a <handoff> document for its downstream nodes; independent branches execute in parallel by dependencies. Return value: {valid, title, nodes, edges, order, errors} where order is the topological execution order and errors lists validation problems (empty = valid). Be self-contained: node prompts must work in a fresh conversation with no access to this one.".to_string(),
                input_schema: json!({
                    "type": "object",
                    "properties": {
                        "title": {
                            "type": "string",
                            "description": "Workflow title (displayed on the graph)"
                        },
                        "nodes": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "id": {
                                        "type": "string",
                                        "description": "Unique node id, e.g. node-1"
                                    },
                                    "name": {
                                        "type": "string",
                                        "description": "Short node name"
                                    },
                                    "label": {
                                        "type": "string",
                                        "description": "Human-readable label rendered on the graph card"
                                    },
                                    "prompt": {
                                        "type": "string",
                                        "description": "Fully self-contained instruction prompt the node's agent executes alone"
                                    },
                                    "description": {
                                        "type": "string",
                                        "description": "One-line description of what this node achieves"
                                    },
                                    "apiProfile": {
                                        "type": "string",
                                        "description": "API config profile name to pin this node to; empty string inherits the current profile"
                                    },
                                    "model": {
                                        "type": "string",
                                        "description": "Model id to pin this node to; empty string inherits the current model"
                                    }
                                },
                                "required": ["id", "name", "prompt"]
                            },
                            "description": "Workflow nodes in execution order"
                        },
                        "edges": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "source": { "type": "string", "description": "Source node id" },
                                    "target": { "type": "string", "description": "Target node id" }
                                },
                                "required": ["source", "target"]
                            },
                            "description": "Directed edges expressing dependencies"
                        }
                    },
                    "required": ["nodes", "edges"]
                }),
            },
            McpTool {
                server_id: SERVER_ID.to_string(),
                name: "workflow-resume".to_string(),
                description: "Resume a failed WorkFlow from its failed node. When the execute result contains `failedNode` with `resumable: true`, first ask the user whether to resume; only call this tool after the user agrees. The runtime reuses the failed node's ORIGINAL conversation and sends a continue prompt there, so the node keeps its full context instead of restarting from scratch; once it succeeds, the remaining nodes run as usual. Parameters: `flowId` (the `failedNode.flowId` from the failed result) and an optional `continuePrompt` (a short instruction for the failed node's agent on how to continue, e.g. the user's fix suggestion). Return value: the same summary shape as the execute result; if the node fails again you may repeat this loop after asking the user.".to_string(),
                input_schema: json!({
                    "type": "object",
                    "properties": {
                        "flowId": {
                            "type": "string",
                            "description": "The flowId from the failed workflow result (the workflow-generate tool call's flow id, found in failedNode.flowId)"
                        },
                        "continuePrompt": {
                            "type": "string",
                            "description": "Optional short instruction sent to the failed node's conversation telling its agent how to continue (e.g. the user's fix suggestion). Omit to simply ask it to continue from where it stopped."
                        }
                    },
                    "required": ["flowId"],
                    "additionalProperties": false
                }),
            },
        ]
    }

    fn execute(&self, tool_name: &str, args: &Value) -> napi::Result<Value> {
        match tool_name {
            "workflow-generate" => self.generate(args),
            "workflow-resume" => Err(Error::new(
                Status::GenericFailure,
                "workflow-resume must be executed through the asynchronous Electron interaction bridge"
                    .to_string(),
            )),
            _ => Err(Error::new(
                Status::InvalidArg,
                format!(
                    "Unknown tool: \"{}\" for MCP server \"workflow\". Available tools: [workflow-workflow-generate, workflow-workflow-resume]",
                    tool_name
                ),
            )),
        }
    }
}
