/**
 * Registry mapping in-flight tool execution ids (the UUIDs emitted by the
 * Rust `tool_execution` stream chunks) to the AbortController that cancels
 * their SSH commands. When the UI stops a conversation it calls
 * `abortToolExecution(id)`; the Electron main process consults this registry
 * so the SSH exec channel is closed in the same synchronous step, instead of
 * relying only on the Rust-side cancellation token (which cannot reach the
 * still-pending Electron promise).
 */
const sshCommandAbortControllers = new Map<string, AbortController>();

export const registerSshCommandAbort = (
  executionId: string,
  controller: AbortController
): void => {
  sshCommandAbortControllers.set(executionId, controller);
};

export const abortSshCommand = (executionId: string): void => {
  const controller = sshCommandAbortControllers.get(executionId);
  if (controller) {
    controller.abort();
    sshCommandAbortControllers.delete(executionId);
  }
};

export const unregisterSshCommandAbort = (executionId: string): void => {
  sshCommandAbortControllers.delete(executionId);
};

/**
 * Registry for checkpoint scan abort controllers, keyed by scan id (one scan
 * id per checkpoint before/after capture round, generated by the Rust side).
 * When the Rust-side checkpoint budget times out it drops its future, but the
 * Electron-side SFTP walk keeps running unless explicitly aborted; Rust then
 * dispatches a `checkpoint-abort-scan` command which looks up this registry
 * and aborts the in-flight scan controller.
 */
const checkpointScanAbortControllers = new Map<string, AbortController>();

export const registerCheckpointScanAbort = (
  scanId: string,
  controller: AbortController
): void => {
  checkpointScanAbortControllers.set(scanId, controller);
};

export const abortCheckpointScan = (scanId: string): boolean => {
  const controller = checkpointScanAbortControllers.get(scanId);
  if (!controller) {
    return false;
  }
  controller.abort();
  // Keep the entry so any follow-up operation of the same scan observes the
  // aborted state; it is removed when the operation settles.
  return true;
};

export const unregisterCheckpointScanAbort = (
  scanId: string,
  controller: AbortController
): void => {
  const current = checkpointScanAbortControllers.get(scanId);
  if (current === controller) {
    checkpointScanAbortControllers.delete(scanId);
  }
};
